[package]
name = "result-transformer"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[features]
default = ["sync"]
full = ["sync", "async", "sync-macros", "async-macros", "sync-derive", "async-derive"]

sync = ["result-transformer-core/sync"]
async = ["result-transformer-core/async"]

sync-macros = ["result-transformer-macros/sync", "sync"]
async-macros = ["result-transformer-macros/async", "async"]

sync-derive = ["result-transformer-derive/sync", "sync"]
async-derive = ["result-transformer-derive/async", "async"]

[dependencies]
result-transformer-dependencies = { path = "../result-transformer-dependencies"}

result-transformer-core = { path = "../result-transformer-core" }
result-transformer-macros = { path = "../result-transformer-macros", optional = true }
result-transformer-derive = { path = "../result-transformer-derive", optional = true }