[package]
name = "result-transformer-flow"
edition.workspace = true
version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description.workspace = true
readme.workspace = true

[dependencies]
result-transformer-dependencies = { path = "../result-transformer-dependencies" ,optional = true, default-features = false}

[features]

sync = []
async = []

logging = ["result-transformer-dependencies/log"]
